spring.application.name=World Clock & Weather
server.port=8081
openweathermap.api.key=1e4fa19db5eb8eaec7690c1960ce7182
# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
# WebClient timeout
spring.webflux.client.max-in-memory-size=2MB
spring.datasource.url=jdbc:h2:file:./data/worldclockdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update